name: CI for branch and PR builds

on:
  push:
    branches-ignore:
      - 'release*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
      - run: npm run cover
      - run: npm install eslint
        env:
          CI: true

      - name: Run ESlint
        run: |
          eslint index.js